name: build and test

on:
  workflow_call:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.22' ] #upload-artifact does not work with multiple builds

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
      - name: Install dependencies
        run: go mod download
      - name: Test with Go
        run: make test
      - name: Build with Go
        run: make build
      - uses: actions/upload-artifact@v4
        with:
          name: binary
          path: kubernetes-git-sync